### ISSUE TITLE
NPE for swagger-ui

### ISSUE THREAD

**Issue by isernikov** [sercasti/spring-httpserver-timings#6]
Hi, I cauth NPE when tried to access Swagger (http://localhost:8080/swagger-ui/).

`java.lang.NullPointerException
	at io.github.sercasti.tracing.domain.HttpServletResponseCopier.isCommitted(HttpServletResponseCopier.java:60)
	at org.springframework.web.servlet.view.InternalResourceView.useInclude(InternalResourceView.java:247)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:158)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1396)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1141)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)`

![image](https://user-images.githubusercontent.com/86324611/138130026-c3d66aaf-298b-4493-9c35-6f33ee92a98b.png)
![image](https://user-images.githubusercontent.com/86324611/138130137-ae908334-87dc-450a-83f3-5eb4b9511774.png)

It looks like copier was not initialized for forwarded requests.

**Comment by sercasti** [comment]
Fixed in version 0.0.6
